INSERT INTO dog_breeds (slug, name_ko, name_en, aliases, popularity_rank, is_mixed, is_unknown) VALUES
('maltese', '몰티즈', 'Maltese', '{"말티즈"}', 1, false, false),
('poodle', '푸들', 'Poodle', '{}', 2, false, false),
('mixed-breed', '믹스견', 'Mixed Breed', '{"믹스", "잡견"}', 3, true, false),
('pomeranian', '포메라니안', 'Pomeranian', '{"포메"}', 4, false, false),
('bichon-frise', '비숑 프리제', 'Bichon Frise', '{"비숑"}', 5, false, false),
('chihuahua', '치와와', 'Chihuahua', '{}', 6, false, false),
('shih-tzu', '시추', 'Shih Tzu', '{}', 7, false, false),
('golden-retriever', '골든 리트리버', 'Golden Retriever', '{"골든"}', 8, false, false),
('jindo-dog', '진돗개', 'Jindo Dog', '{"진돗개", "한국 토종견"}', 9, false, false),
('yorkshire-terrier', '요크셔 테리어', 'Yorkshire Terrier', '{"요키"}', 10, false, false),
('shiba-inu', '시바견', 'Shiba Inu', '{"시바이누"}', 11, false, false),
('border-collie', '볼더 콜리', 'Border Collie', '{}', 12, false, false),
('labrador-retriever', '래브라도 리트리버', 'Labrador Retriever', '{"래브라도"}', 13, false, false),
('samoyed', '사모예드', 'Samoyed', '{"사모"}', 14, false, false),
('dachshund', '닥스훈트', 'Dachshund', '{"소시지개"}', 15, false, false),
('welsh-corgi', '웰시코기', 'Welsh Corgi', '{}', 16, false, false),
('miniature-schnauzer', '미니어처 슈나우저', 'Miniature Schnauzer', '{"슈나우저"}', 17, false, false),
('japanese-spitz', '일본 스피츠', 'Japanese Spitz', '{"재패니즈 스피츠", "제페니즈 스피츠"}', 18, false, false),
('boston-terrier', '보스턴 테리어', 'Boston Terrier', '{"보스턴"}', 19, false, false),
('pekingese', '페키니즈', 'Pekingese', '{}', 20, false, false),
('cocker-spaniel', '코커 스파니엘', 'Cocker Spaniel', '{"코커"}', 21, false, false),
('miniature-pinscher', '미니어처 핀셔', 'Miniature Pinscher', '{"미니핀"}', 22, false, false),
('german-shepherd', '저먼 셰퍼드', 'German Shepherd', '{"셰퍼드"}', 23, false, false),
('beagle', '비글', 'Beagle', '{}', 24, false, false),
('bulldog', '불독', 'Bulldog', '{}', 25, false, false),
('papillon', '뽀삐용', 'Papillon', '{}', 26, false, false),
('siberian-husky', '시베리안 허스키', 'Siberian Husky', '{"허스키"}', 27, false, false),
('doberman', '도베른', 'Doberman', '{"도베른 핀셔"}', 28, false, false),
('boxer', '복서', 'Boxer', '{}', 29, false, false),
('miniature-bull-terrier', '미니어처 불테리어', 'Miniature Bull Terrier', '{"미니불"}', 30, false, false),
('american-staffordshire-terrier', '아메리칸 불테리어', 'American Staffordshire Terrier', '{"스태퍼드셔 불테리어"}', 31, false, false),
('standard-schnauzer', '스탠다드 슈나우저', 'Standard Schnauzer', '{}', 32, false, false),
('scottish-terrier', '스코티시 테리어', 'Scottish Terrier', '{"스코티"}', 33, false, false),
('west-highland-white-terrier', '웨스트 하이랜드 화이트 테리어', 'West Highland White Terrier', '{"웨스티"}', 34, false, false),
('jack-russell-terrier', '잭 러셀 테리어', 'Jack Russell Terrier', '{"잭러셀"}', 35, false, false),
('fox-terrier', '폭스 테리어', 'Fox Terrier', '{}', 36, false, false),
('pungsan-dog', '풍산개', 'Pungsan Dog', '{"한국 토종견"}', 37, false, false),
('sapsaree', '삽살개', 'Sapsaree', '{"삽살이", "한국 토종견"}', 38, false, false),
('saint-bernard', '세인트 버나드', 'Saint Bernard', '{}', 39, false, false),
('great-dane', '그레이트 데인', 'Great Dane', '{}', 40, false, false),
('bernese-mountain-dog', '버니즈 마운틴 독', 'Bernese Mountain Dog', '{"버니즈"}', 41, false, false),
('newfoundland', '뉴펀들랜드', 'Newfoundland', '{}', 42, false, false),
('rottweiler', '로트와일러', 'Rottweiler', '{}', 43, false, false),
('akita', '아키타', 'Akita', '{}', 44, false, false),
('alaskan-malamute', '알래스칸 말라뮤트', 'Alaskan Malamute', '{"말라뮤트"}', 45, false, false),
('bedlington-terrier', '베들링턴 테리어', 'Bedlington Terrier', '{}', 46, false, false),
('manchester-terrier', '맨체스터 테리어', 'Manchester Terrier', '{}', 47, false, false),
('silky-terrier', '실키 테리어', 'Silky Terrier', '{}', 48, false, false),
('greyhound', '그레이하운드', 'Greyhound', '{}', 49, false, false),
('whippet', '위펫', 'Whippet', '{}', 50, false, false);
