INSERT INTO cat_breeds (slug, name_ko, name_en, aliases, popularity_rank, is_mixed, is_unknown) VALUES
('korean-shorthair', '코리안 숏헤어', 'Korean Shorthair', '{"코숏", "토종고양이", "한국 고양이"}', 1, false, false),
('russian-blue', '러시안 블루', 'Russian Blue', '{}', 2, false, false),
('persian', '페르시안', 'Persian', '{}', 3, false, false),
('scottish-fold', '스코티시 폴드', 'Scottish Fold', '{}', 4, false, false),
('siamese', '샴', 'Siamese', '{"샴고양이"}', 5, false, false),
('british-shorthair', '브리티시 숏헤어', 'British Shorthair', '{"브숏"}', 6, false, false),
('munchkin', '먼치킨', 'Munchkin', '{"닭다리고양이"}', 7, false, false),
('turkish-angora', '터키시 앙고라', 'Turkish Angora', '{}', 8, false, false),
('ragdoll', '랙돌', 'Ragdoll', '{"래그돌"}', 9, false, false),
('american-shorthair', '아메리칸 숏헤어', 'American Shorthair', '{"아메숏"}', 10, false, false),
('abyssinian', '아비시니안', 'Abyssinian', '{}', 11, false, false),
('maine-coon', '메인쿤', 'Maine Coon', '{}', 12, false, false),
('bengal', '벵갈', 'Bengal', '{}', 13, false, false),
('norwegian-forest-cat', '노르웨이 숲', 'Norwegian Forest Cat', '{}', 14, false, false),
('sphynx', '스핑크스', 'Sphynx', '{"무털고양이"}', 15, false, false),
('birman', '버만', 'Birman', '{}', 16, false, false),
('american-curl', '아메리칸 컬', 'American Curl', '{}', 17, false, false),
('devon-rex', '데본 렉스', 'Devon Rex', '{}', 18, false, false),
('manx', '맹스', 'Manx', '{}', 19, false, false),
('selkirk-rex', '셀커크 렉스', 'Selkirk Rex', '{}', 20, false, false);
